### PR TITLE
fix link to AMD docs

### PR DESCRIPTION
**Pull request by datosh**
Link has changed

### CODE REVIEW

**Comment by datosh** [comment]
@deeglaze why did you close the PR? Is the link working for you, or anything missing for it to be merged?

**Comment by deeglaze** [comment]
Sorry, I must have closed this in my sleep. There's another wp-content link in verify/trust/trust.go that should be fixed as well. Would you change that one too, please?

**Comment by datosh** [comment]
PTAL @deeglaze 
I am not sure what the other dead link served before. From the name `ask_ark_milan.cert` I suspect it is the same as VCEK chain.

**Comment by deeglaze** [comment]
It is not the same. The contents are in the SEV ABI format for public keys. The link is also broken in AMD's repo, which I propose a fix here: https://github.com/AMDESE/sev-guest/pull/42/files

**Review by deeglaze — APPROVED** [review]

**Comment by deeglaze** [comment]
Thanks!

**Pull request merged**
